controllers:
    resource: ../src/Controller/
    type: attribute


createLogistics:
    path: /createLogistics
    controller: App\Controller\LogisticsController::createLogistics

showHistoryLogistics:
    path: /showHistoryLogistics/{id}
    controller: App\Controller\LogisticsController::showHistoryLogistics

setStatusLogistics:
    path: /setStatusLogistics
    controller: App\Controller\LogisticsController::setStatusLogistics
